services:
  - type: web
    name: todolist-projeto-2
    runtime: node
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: STATIC_EXPORT
        value: "1"
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
