services:
  - type: web
    name: todolist-projeto-2
    runtime: node
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: npm install && npm install --prefix web && npm run build:export --prefix web
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
